package com.seffafbagis.api.enums;

public enum NotificationType {
    DONATION_RECEIVED,
    DONATION_COMPLETED,
    CAMPAIGN_UPDATE,
    CAMPAIGN_COMPLETED,
    CAMPAIGN_APPROVED,
    CAMPAIGN_REJECTED,
    EVIDENCE_REQUIRED,
    EVIDENCE_APPROVED,
    EVIDENCE_REJECTED,
    SCORE_CHANGE,
    APPLICATION_UPDATE,
    BANK_TRANSFER_EXPIRED,
    SYSTEM
}
