// Mock admin data

import type {
  AdminUser,
  AdminOrganization,
  AdminCampaign,
  AdminDonation,
  AdminEvidence,
  AdminReport,
  SystemSetting,
  AuditLog,
  DashboardStats,
} from '@/types/admin';

export const mockUsers: AdminUser[] = [
  {
    id: '1',
    email: 'admin@example.com',
    role: 'admin',
    status: 'active',
    email_verified: true,
    failed_login_attempts: 0,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user_foundation_1',
    email: 'foundation@example.com',
    role: 'foundation',
    status: 'active',
    email_verified: true,
    failed_login_attempts: 0,
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-01-15T00:00:00Z',
  },
  {
    id: '2',
    email: 'donor@example.com',
    role: 'donor',
    status: 'active',
    email_verified: true,
    failed_login_attempts: 0,
    created_at: '2024-02-01T00:00:00Z',
    updated_at: '2024-02-01T00:00:00Z',
  },
  {
    id: '3',
    email: 'suspended@example.com',
    role: 'donor',
    status: 'suspended',
    email_verified: true,
    failed_login_attempts: 3,
    locked_until: '2025-01-01T00:00:00Z',
    created_at: '2024-03-01T00:00:00Z',
    updated_at: '2024-12-20T00:00:00Z',
  },
];

export const mockOrganizations: AdminOrganization[] = [
  {
    id: 'org_1',
    user_id: 'user_foundation_1',
    legal_name: 'Hope Foundation Turkey',
    trade_name: 'Hope Foundation',
    organization_type: 'foundation',
    verification_status: 'approved',
    is_featured: true,
    verified_at: '2024-01-20T00:00:00Z',
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-01-20T00:00:00Z',
  },
  {
    id: 'org_2',
    user_id: 'user_4',
    legal_name: 'Education First Association',
    organization_type: 'association',
    verification_status: 'pending',
    is_featured: false,
    created_at: '2024-12-20T00:00:00Z',
    updated_at: '2024-12-20T00:00:00Z',
  },
  {
    id: 'org_3',
    user_id: 'user_5',
    legal_name: 'Green Earth NGO',
    organization_type: 'ngo',
    verification_status: 'in_review',
    is_featured: false,
    created_at: '2024-12-15T00:00:00Z',
    updated_at: '2024-12-18T00:00:00Z',
  },
];

export const mockCampaigns: AdminCampaign[] = [
  {
    id: 'camp_1',
    organization_id: 'org_1',
    title: 'Books for Rural Schools',
    status: 'active',
    goal_amount: 50000,
    collected_amount: 35000,
    donor_count: 142,
    currency: 'TRY',
    is_featured: true,
    is_urgent: false,
    created_at: '2024-10-25T00:00:00Z',
    updated_at: '2024-12-20T00:00:00Z',
  },
  {
    id: 'camp_2',
    organization_id: 'org_1',
    title: 'Mobile Health Clinic',
    status: 'completed',
    goal_amount: 100000,
    collected_amount: 100000,
    donor_count: 256,
    currency: 'TRY',
    is_featured: false,
    is_urgent: false,
    created_at: '2024-06-01T00:00:00Z',
    updated_at: '2024-12-01T00:00:00Z',
  },
  {
    id: 'camp_3',
    organization_id: 'org_2',
    title: 'University Scholarships 2025',
    status: 'pending_approval',
    goal_amount: 200000,
    collected_amount: 0,
    donor_count: 0,
    currency: 'TRY',
    is_featured: false,
    is_urgent: true,
    created_at: '2024-12-20T00:00:00Z',
    updated_at: '2024-12-20T00:00:00Z',
  },
];

export const mockDonations: AdminDonation[] = [
  {
    id: 'don_1',
    user_id: '2',
    campaign_id: 'camp_1',
    amount: 500,
    currency: 'TRY',
    status: 'completed',
    is_anonymous: false,
    payment_method: 'credit_card',
    created_at: '2024-12-20T10:30:00Z',
  },
  {
    id: 'don_2',
    user_id: '3',
    campaign_id: 'camp_1',
    amount: 1000,
    currency: 'TRY',
    status: 'completed',
    is_anonymous: true,
    payment_method: 'bank_transfer',
    created_at: '2024-12-19T14:20:00Z',
  },
  {
    id: 'don_3',
    user_id: '2',
    campaign_id: 'camp_2',
    amount: 250,
    currency: 'TRY',
    status: 'pending',
    is_anonymous: false,
    payment_method: 'credit_card',
    created_at: '2024-12-21T09:15:00Z',
  },
];

export const mockEvidences: AdminEvidence[] = [
  {
    id: 'evi_1',
    campaign_id: 'camp_1',
    title: 'Book Purchase Receipt - December',
    description: 'Receipt for 500 textbooks purchased from Publisher A',
    evidence_type: 'receipt',
    status: 'approved',
    amount_spent: 15000,
    vendor_name: 'ABC Publishers',
    uploaded_at: '2024-12-10T00:00:00Z',
    reviewed_at: '2024-12-11T00:00:00Z',
    reviewer_id: '1',
  },
  {
    id: 'evi_2',
    campaign_id: 'camp_1',
    title: 'Distribution Photos - Rural School Visit',
    evidence_type: 'photo',
    status: 'pending',
    uploaded_at: '2024-12-20T00:00:00Z',
  },
  {
    id: 'evi_3',
    campaign_id: 'camp_2',
    title: 'Medical Equipment Invoice',
    evidence_type: 'invoice',
    status: 'approved',
    amount_spent: 45000,
    vendor_name: 'Medical Supplies Inc',
    uploaded_at: '2024-11-15T00:00:00Z',
    reviewed_at: '2024-11-16T00:00:00Z',
    reviewer_id: '1',
  },
];

export const mockReports: AdminReport[] = [
  {
    id: 'rep_1',
    reporter_id: '2',
    report_type: 'fraud',
    entity_type: 'campaign',
    entity_id: 'camp_3',
    status: 'pending',
    priority: 'high',
    description: 'Suspicious campaign with unrealistic goals',
    created_at: '2024-12-20T00:00:00Z',
    updated_at: '2024-12-20T00:00:00Z',
  },
  {
    id: 'rep_2',
    reporter_id: '3',
    report_type: 'inappropriate_content',
    entity_type: 'campaign',
    entity_id: 'camp_1',
    status: 'resolved',
    priority: 'low',
    description: 'Image quality is poor',
    assigned_to: '1',
    resolved_at: '2024-12-15T00:00:00Z',
    created_at: '2024-12-10T00:00:00Z',
    updated_at: '2024-12-15T00:00:00Z',
  },
];

export const mockSystemSettings: SystemSetting[] = [
  {
    id: 'set_1',
    setting_key: 'platform_fee_percentage',
    setting_value: '2.5',
    value_type: 'number',
    is_public: true,
    description: 'Platform fee percentage for donations',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'set_2',
    setting_key: 'min_donation_amount',
    setting_value: '10',
    value_type: 'number',
    is_public: true,
    description: 'Minimum donation amount in TRY',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'set_3',
    setting_key: 'email_notifications_enabled',
    setting_value: 'true',
    value_type: 'boolean',
    is_public: false,
    description: 'Enable email notifications',
    updated_at: '2024-06-01T00:00:00Z',
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    id: 'log_1',
    user_id: '1',
    action: 'organization.verified',
    entity_type: 'organization',
    entity_id: 'org_1',
    old_values: { verification_status: 'pending' },
    new_values: { verification_status: 'approved' },
    ip_address: '192.168.1.1',
    created_at: '2024-01-20T00:00:00Z',
  },
  {
    id: 'log_2',
    user_id: '1',
    action: 'campaign.approved',
    entity_type: 'campaign',
    entity_id: 'camp_1',
    old_values: { status: 'pending_approval' },
    new_values: { status: 'active' },
    ip_address: '192.168.1.1',
    created_at: '2024-10-26T00:00:00Z',
  },
  {
    id: 'log_3',
    user_id: '1',
    action: 'evidence.approved',
    entity_type: 'evidence',
    entity_id: 'evi_1',
    old_values: { status: 'pending' },
    new_values: { status: 'approved' },
    ip_address: '192.168.1.1',
    created_at: '2024-12-11T00:00:00Z',
  },
];

export const mockDashboardStats: DashboardStats = {
  total_users: 4,
  pending_org_verifications: 2,
  pending_campaign_approvals: 1,
  pending_evidence_reviews: 1,
  pending_reports: 1,
  total_donations_today: 2,
  total_amount_today: 1500,
};
